[theme]
base = "light"
primaryColor = "#1F5B3F"
backgroundColor = "#EEF1F4"
secondaryBackgroundColor = "#F6F8F9"
textColor = "#14202B"
font = "sans serif"

[server]
maxUploadSize = 60
headless = true

[browser]
gatherUsageStats = false
